# Generated by Django 5.0.3 on 2024-03-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_roomcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcode',
            name='room',
        ),
        migrations.AddField(
            model_name='roomcode',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='rooms.questroom'),
            preserve_default=False,
        ),
    ]
