# Generated by Django 5.0.3 on 2024-03-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_remove_roomcode_room_roomcode_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcode',
            old_name='room_id',
            new_name='room',
        ),
    ]
