# Generated by Django 5.0.3 on 2024-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('CH', 'Chat'), ('UC', 'User Connected'), ('UJ', 'User Joined'), ('UL', 'User Left')], default='CH', max_length=2),
        ),
    ]
