# Generated by Django 5.0.3 on 2024-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_questroomscore_delete_questroomuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questroomscore',
            old_name='total_solved',
            new_name='total_solved_before_joining',
        ),
        migrations.AddField(
            model_name='questroomscore',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
