# Generated by Django 5.0.3 on 2024-04-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_rename_total_solved_questroomscore_total_solved_before_joining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questroomscore',
            old_name='total_solved_before_joining',
            new_name='score_before_joining',
        ),
    ]
