# Generated by Django 5.0.3 on 2024-04-07 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_rename_total_solved_before_joining_questroomscore_score_before_joining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questroomscore',
            unique_together={('room', 'user')},
        ),
    ]
