# Generated by Django 5.0.3 on 2024-04-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0027_alter_questroomscore_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questroomscore',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questroom_score', to='rooms.questroom'),
        ),
    ]
