services:
  redis:
    image: "redis:alpine"

  django:
    container_name: django
    build: 
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=09dfjsldfjsoiejnwievnwlkdnv
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build: 
      context: ./
    command: celery -A core worker -l INFO -B -E
    volumes:
      - ./:/usr/src/app
    environment:
      - DEBUG=True
      - SECRET_KEY=09dfjsldfjsoiejnwievnwlkdnv
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis