# Generated by Django 5.0.3 on 2024-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questroom',
            name='expire_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
