# Generated by Django 5.0.3 on 2024-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_questroom_daily_required_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questroom',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
