# Generated by Django 5.0.3 on 2024-03-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_alter_questroom_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questroom',
            options={'permissions': [('can_send_message', 'Can send message in room'), ('can_remove_user', 'Can remove user from room'), ('can_add_user', 'Can add user to room'), ('can_make_admin', 'Can make room member admin'), ('can_generate_roomcode', 'Can generate room code')]},
        ),
    ]
