# Generated by Django 5.0.3 on 2024-04-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_alter_questroom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('CH', 'Chat'), ('UJ', 'User Joined'), ('UL', 'User Left')], default='CH', max_length=2),
        ),
    ]
